baseURL = "https://blog.eldrmedia.com"
languageCode = "en-us"
title = "ELDR MEDIA Blog"
theme = "default"

paginate = 6
[social]
  github = "https://github.com/eldrmedia"
  instagram = "https://www.instagram.com/eldrmedia/"
  linkedin = "https://www.linkedin.com/in/williamelder/"

[taxonomies]
  author = "authors"